name: Test

on:
  push:
    branches:
      - 'main'
  pull_request:

concurrency:
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.8'
      - name: Set up C++
        run: |
          sudo apt install -y --no-install-recommends build-essential
          g++ --version
      - name: Run algorithm code tests
        run: |
          ./test.sh
        working-directory: test
